version: '3.7'

services:

  app:
    image: cockroachapp
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dc2-network
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on: 
      - db
      
  db:
     image: cockroachdb/cockroach
     ports:
       - "26257:26257"
       - "8080:8080"
     run: cockroach sql --execute="create database tododb;" --insecure
     # command: start-single-node --insecure
     entrypoint:
      - bash
      - "-c"
      - cockroach sql --insecure -e "CREATE IF NOT EXIST DATABASE tododb;" &
        exec cockroach start-single-node --insecure

     networks:
       - dc2-network

     volumes:
       - cockroachdata:/cockroach/cockroach-data
volumes:
  cockroachdata:
   

networks:
  dc2-network:
    driver: bridge
